<a href="https://colab.research.google.com/github/grjadhav409/Enthalpy-prediction-ML/blob/main/1_smiles_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# smiles calculation

in this notebook SMILES representations are calculated from there IUPAC or common names

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
alkane = "/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/alkanes.xlsx"
alkene="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/alkene.xlsx"
alkyne="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/alkyne.xlsx"
diene="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/diene.xlsx"
RCH3="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/RCH3.xlsx"
R4C="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/R4C.xlsx"
R3CH="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/R3CH.xlsx"
R2CH2="/content/drive/MyDrive/Colab Notebooks/data2/Enthalpy of formation enthalpy of formation/hydrocarbans/R2CH2.xlsx"

In [ ]:
df1 = pd.read_excel(alkane)
df2 = pd.read_excel(alkene)
df3 = pd.read_excel(alkyne)
df4 = pd.read_excel(diene)
df5 = pd.read_excel(RCH3)
df6 = pd.read_excel(R4C)
df7 = pd.read_excel(R3CH)
df8 = pd.read_excel(R2CH2)

In [ ]:
df= pd.concat([df1,df2,df3,df4,df5,df6,df7,df8])
df = df.drop(["species1","species2","species3",'species4',"hfg_0K"],axis=1)
df

                                    name  charge         species      hfg
0                                 Decane       0          C10H22  -249.70
1                                 Nonane       0           C9H20  -228.30
2                      tetramethylbutane       0  (CH3)3CC(CH3)3  -226.20
3                                 Octane       0           C8H18  -208.40
4                         2-methylhexane       0           C7H16  -195.00
..                                   ...     ...             ...      ...
252           Bicyclo[2.2.0]hex-1(4)-ene       0            C6H8   303.76
253  Bicyclo[1.1.0]butane-1-carbonitrile       0           C5H5N   304.51
254             Bicyclo[2.1.0]pent-2-ene       0            C5H6   333.05
255                        Quadricyclane       0            C7H8   336.00
256                 cyclopropenyl cation       1           C3H3+  1080.00

[821 rows x 4 columns]

In [ ]:
from urllib.request import urlopen
from urllib.parse import quote

def CIRconvert(ids):
    try:
        url = 'http://cactus.nci.nih.gov/chemical/structure/' + quote(ids) + '/smiles'
        ans = urlopen(url).read().decode('utf8')
        return ans
    except:
        return 'Did not work'

#identifiers  = ['3-Methylheptane', 'Aspirin', 'Diethylsulfate', 'Diethyl sulfate', '50-78-2', 'Adamant']
identifiers = df['name'].tolist()
d= []
for ids in identifiers :
    #print(ids, CIRconvert(ids))
    d.append(
        {
            'name': ids,
            'SMILES':CIRconvert(ids) 
        }
    )

dfwithsmiles = pd.DataFrame(d)
dfwithsmiles

                                    name           SMILES
0                                 Decane       CCCCCCCCCC
1                                 Nonane        CCCCCCCCC
2                      tetramethylbutane   CCC(C)C(C)(C)C
3                                 Octane         CCCCCCCC
4                         2-methylhexane        CCCCC(C)C
..                                   ...              ...
816           Bicyclo[2.2.0]hex-1(4)-ene      C1CC2=C1CC2
817  Bicyclo[1.1.0]butane-1-carbonitrile      N#CC12CC1C2
818             Bicyclo[2.1.0]pent-2-ene       C1C2C=CC12
819                        Quadricyclane  C1C2C3C2C4C1C34
820                 cyclopropenyl cation     Did not work

[821 rows x 2 columns]

In [ ]:
 dataframe = pd.merge(df, dfwithsmiles, on='name')

In [ ]:
dataframe

                         name  charge species      hfg               SMILES
0                      Decane       0  C10H22  -249.70           CCCCCCCCCC
1                      Decane       0  C10H22  -249.70           CCCCCCCCCC
2                      Decane       0  C10H22  -249.70           CCCCCCCCCC
3                      Decane       0  C10H22  -249.70           CCCCCCCCCC
4                      Decane       0  C10H22  -249.70           CCCCCCCCCC
...                       ...     ...     ...      ...                  ...
1898                Aziridine       0   C2H5N   126.00                C1CN1
1899  Cyclobutanecarbonitrile       0   C5H7N   147.30            N#CC1CCC1
1900                 Fluorene       0  C13H10   176.70  C1c2ccccc2c3ccccc13
1901           Succinonitrile       0  C4H4N2   209.66             N#CCCC#N
1902     cyclopropenyl cation       1   C3H3+  1080.00         Did not work

[1903 rows x 5 columns]